stages:
  - build
  - test

build:
  stage: build
  script: mvn package
  image: maven:3.3.9-jdk-8
  artifacts:
    paths:
      - target/*.jar

test:
  image: docker:latest
  services:
    - docker:dind
  stage: test
  script: docker build .